---
- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started

- name: Create a Docker network
  docker_network:
    name: web_network
    state: present

- name: Create Docker volume for HTML files
  docker_volume:
    name: web_volume
    state: present

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    networks:
      - name: web_network
    volumes:
      - web_volume:/usr/share/nginx/html

- name: Copy HTML file to Docker volume
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../roles/nginx/files/index.html"
    dest: "/var/lib/docker/volumes/web_volume/_data/index.html"